//
//  Universities.swift
//  Pittu_UniversityApp
//
//  Created by Pittu,Sobhareddy on 4/18/23.
//

import Foundation


struct Universities{
    var domain = ""
    var universitiesList:[UniversityList] = []
}
struct UniversityList{
    var collegeName = ""
    var collegeImage  = ""
    var collegeInfo = ""
}
let u1 = Universities(domain: "Computer Science", universitiesList: [UniversityList(collegeName: "Northwest Missouri State University", collegeImage: "nwmsu", collegeInfo: "Northwest Missouri State University is a public university in Maryville, Missouri. It has an enrollment of about 8,505 students. Founded in 1905 as a teachers college, its campus is based on the design for Forest Park at the 1904 St. Louis World's Fair and is the official Missouri State Arboretum."),UniversityList(collegeName: "Wright State University", collegeImage: "wsu", collegeInfo: "Wright State University is a public research university in Fairborn, Ohio. Originally opened in 1964 as a branch campus of Miami University and Ohio State University, it became an independent institution in 1967 and was named in honor of aviation pioneers Orville and Wilbur Wright, who were Dayton residents."),UniversityList(collegeName: "Texas State University", collegeImage: "tsu", collegeInfo: "Texas State University is a public research university with its main campus located in the southern portion of the Austin metropolitan area, and its Round Rock campus in the northern portion. "),UniversityList(collegeName: "University of Central Missouri", collegeImage: "ucm", collegeInfo: "The University of Central Missouri (UCM) is a public university in Warrensburg, Missouri. In 2019, enrollment was 11,229 students[5] from 49 states and 59 countries on its 1,561-acre campus. UCM offers 150 programs of study, including 10 pre-professional programs, 27 areas of teacher certification, and 37 graduate programs."),UniversityList(collegeName: "University of Missouri - Kansas City", collegeImage: "umkc", collegeInfo: "The University of Missouri–Kansas City is a public research university in Kansas City, Missouri. UMKC is part of the University of Missouri System and one of only two member universities with a medical school. As of 2020, the university's enrollment exceeded 16,000 students."),UniversityList(collegeName: "University of Cincinatti", collegeImage: "uoc", collegeInfo: "The University of Cincinnati is a public research university in Cincinnati, Ohio. Founded in 1819 as Cincinnati College, it is the oldest institution of higher education in Cincinnati and has an annual enrollment of over 44,000 students, making it the second largest university in Ohio.")])

let u2 = Universities(domain: "Information Systems", universitiesList: [UniversityList(collegeName: "Northwest Missouri State University", collegeImage: "nwmsu", collegeInfo: "Northwest Missouri State University is a public university in Maryville, Missouri. It has an enrollment of about 8,505 students. Founded in 1905 as a teachers college, its campus is based on the design for Forest Park at the 1904 St. Louis World's Fair and is the official Missouri State Arboretum."),UniversityList(collegeName: "Standford University", collegeImage: "su", collegeInfo: "Stanford University, officially Leland Stanford Junior University, is a private research university in Stanford, California. The campus occupies 8,180 acres, among the largest in the United States, and enrolls over 17,000 students."), UniversityList(collegeName: "Hadvord University", collegeImage: "hu", collegeInfo: "Harvard University is a private Ivy League research university in Cambridge, Massachusetts. Founded in 1636 as Harvard College and named for its first benefactor, the Puritan clergyman John Harvard, it is the oldest institution of higher learning in the United States"),UniversityList(collegeName: "Wright State University", collegeImage: "wsu", collegeInfo: "Wright State University is a public research university in Fairborn, Ohio. Originally opened in 1964 as a branch campus of Miami University and Ohio State University, it became an independent institution in 1967 and was named in honor of aviation pioneers Orville and Wilbur Wright, who were Dayton residents."),UniversityList(collegeName: "Texas State University", collegeImage: "tsu", collegeInfo: "Texas State University is a public research university with its main campus located in the southern portion of the Austin metropolitan area, and its Round Rock campus in the northern portion. "),UniversityList(collegeName: "University of Cincinatti", collegeImage: "uoc", collegeInfo: "The University of Cincinnati is a public research university in Cincinnati, Ohio. Founded in 1819 as Cincinnati College, it is the oldest institution of higher education in Cincinnati and has an annual enrollment of over 44,000 students, making it the second largest university in Ohio.")])

let u3 = Universities(domain: "Embedded Systems", universitiesList: [UniversityList(collegeName: "Northwest Missouri State University", collegeImage: "nwmsu", collegeInfo: "Northwest Missouri State University is a public university in Maryville, Missouri. It has an enrollment of about 8,505 students. Founded in 1905 as a teachers college, its campus is based on the design for Forest Park at the 1904 St. Louis World's Fair and is the official Missouri State Arboretum."),UniversityList(collegeName: "Wright State University", collegeImage: "wsu", collegeInfo: "Wright State University is a public research university in Fairborn, Ohio. Originally opened in 1964 as a branch campus of Miami University and Ohio State University, it became an independent institution in 1967 and was named in honor of aviation pioneers Orville and Wilbur Wright, who were Dayton residents."),UniversityList(collegeName: "Texas State University", collegeImage: "tsu", collegeInfo: "Texas State University is a public research university with its main campus located in the southern portion of the Austin metropolitan area, and its Round Rock campus in the northern portion. "),UniversityList(collegeName: "University of Central Missouri", collegeImage: "ucm", collegeInfo: "The University of Central Missouri (UCM) is a public university in Warrensburg, Missouri. In 2019, enrollment was 11,229 students[5] from 49 states and 59 countries on its 1,561-acre campus. UCM offers 150 programs of study, including 10 pre-professional programs, 27 areas of teacher certification, and 37 graduate programs."),UniversityList(collegeName: "University of Missouri - Kansas City", collegeImage: "umkc", collegeInfo: "The University of Missouri–Kansas City is a public research university in Kansas City, Missouri. UMKC is part of the University of Missouri System and one of only two member universities with a medical school. As of 2020, the university's enrollment exceeded 16,000 students."),UniversityList(collegeName: "University of Cincinatti", collegeImage: "uoc", collegeInfo: "The University of Cincinnati is a public research university in Cincinnati, Ohio. Founded in 1819 as Cincinnati College, it is the oldest institution of higher education in Cincinnati and has an annual enrollment of over 44,000 students, making it the second largest university in Ohio.")])

let u4 = Universities(domain: "Data Science", universitiesList: [UniversityList(collegeName: "Standford University", collegeImage: "su", collegeInfo: "Stanford University, officially Leland Stanford Junior University, is a private research university in Stanford, California. The campus occupies 8,180 acres, among the largest in the United States, and enrolls over 17,000 students."), UniversityList(collegeName: "Hadvord University", collegeImage: "hu", collegeInfo: "Harvard University is a private Ivy League research university in Cambridge, Massachusetts. Founded in 1636 as Harvard College and named for its first benefactor, the Puritan clergyman John Harvard, it is the oldest institution of higher learning in the United States"),UniversityList(collegeName: "University of Texsas", collegeImage: "ut", collegeInfo: "The University of Texas at Austin is a public research university in Austin, Texas, and the flagship institution of the University of Texas System. With 40,916 undergraduate students, 11,075 graduate students and 3,133 teaching faculty as of Fall 2021, it is also the largest institution in the system") ,UniversityList(collegeName: "Yale University", collegeImage: "yu", collegeInfo: "Yale University is the second oldest Ivy League institution, founded in New Haven, CT. The school is known for its highly-regarded programs in history, economics, psychology and English. Students are assigned to one of fourteen residential colleges on the school’s campus. Students are associated with their respective colleges throughout their time as undergraduates. Yale encourages their students to venture into unknown academic fields. They provide undergraduates over 1,200 research opportunities in science and technology."),UniversityList(collegeName: "Northwest Missouri State University", collegeImage: "nwmsu", collegeInfo: "Northwest Missouri State University is a public university in Maryville, Missouri. It has an enrollment of about 8,505 students. Founded in 1905 as a teachers college, its campus is based on the design for Forest Park at the 1904 St. Louis World's Fair and is the official Missouri State Arboretum."),UniversityList(collegeName: "Wright State University", collegeImage: "wsu", collegeInfo: "Wright State University is a public research university in Fairborn, Ohio. Originally opened in 1964 as a branch campus of Miami University and Ohio State University, it became an independent institution in 1967 and was named in honor of aviation pioneers Orville and Wilbur Wright, who were Dayton residents.")])

let u5 = Universities(domain: "Cyber Security", universitiesList: [UniversityList(collegeName: "Northwest Missouri State University", collegeImage: "nwmsu", collegeInfo: "Northwest Missouri State University is a public university in Maryville, Missouri. It has an enrollment of about 8,505 students. Founded in 1905 as a teachers college, its campus is based on the design for Forest Park at the 1904 St. Louis World's Fair and is the official Missouri State Arboretum."),UniversityList(collegeName: "Wright State University", collegeImage: "wsu", collegeInfo: "Wright State University is a public research university in Fairborn, Ohio. Originally opened in 1964 as a branch campus of Miami University and Ohio State University, it became an independent institution in 1967 and was named in honor of aviation pioneers Orville and Wilbur Wright, who were Dayton residents."),UniversityList(collegeName: "Texas State University", collegeImage: "tsu", collegeInfo: "Texas State University is a public research university with its main campus located in the southern portion of the Austin metropolitan area, and its Round Rock campus in the northern portion. "),UniversityList(collegeName: "Standford University", collegeImage: "su", collegeInfo: "Stanford University, officially Leland Stanford Junior University, is a private research university in Stanford, California. The campus occupies 8,180 acres, among the largest in the United States, and enrolls over 17,000 students."), UniversityList(collegeName: "Hadvord University", collegeImage: "hu", collegeInfo: "Harvard University is a private Ivy League research university in Cambridge, Massachusetts. Founded in 1636 as Harvard College and named for its first benefactor, the Puritan clergyman John Harvard, it is the oldest institution of higher learning in the United States"),UniversityList(collegeName: "University of Texsas", collegeImage: "ut", collegeInfo: "The University of Texas at Austin is a public research university in Austin, Texas, and the flagship institution of the University of Texas System. With 40,916 undergraduate students, 11,075 graduate students and 3,133 teaching faculty as of Fall 2021, it is also the largest institution in the system") ,UniversityList(collegeName: "Yale University", collegeImage: "yu", collegeInfo: "Yale University is the second oldest Ivy League institution, founded in New Haven, CT. The school is known for its highly-regarded programs in history, economics, psychology and English. Students are assigned to one of fourteen residential colleges on the school’s campus. Students are associated with their respective colleges throughout their time as undergraduates. Yale encourages their students to venture into unknown academic fields. They provide undergraduates over 1,200 research opportunities in science and technology.")])

let u6 = Universities(domain: "Aeronotics", universitiesList: [UniversityList(collegeName: "Standford University", collegeImage: "su", collegeInfo: "Stanford University, officially Leland Stanford Junior University, is a private research university in Stanford, California. The campus occupies 8,180 acres, among the largest in the United States, and enrolls over 17,000 students."), UniversityList(collegeName: "Hadvord University", collegeImage: "hu", collegeInfo: "Harvard University is a private Ivy League research university in Cambridge, Massachusetts. Founded in 1636 as Harvard College and named for its first benefactor, the Puritan clergyman John Harvard, it is the oldest institution of higher learning in the United States"),UniversityList(collegeName: "University of Texsas", collegeImage: "ut", collegeInfo: "The University of Texas at Austin is a public research university in Austin, Texas, and the flagship institution of the University of Texas System. With 40,916 undergraduate students, 11,075 graduate students and 3,133 teaching faculty as of Fall 2021, it is also the largest institution in the system") ,UniversityList(collegeName: "Yale University", collegeImage: "yu", collegeInfo: "Yale University is the second oldest Ivy League institution, founded in New Haven, CT. The school is known for its highly-regarded programs in history, economics, psychology and English. Students are assigned to one of fourteen residential colleges on the school’s campus. Students are associated with their respective colleges throughout their time as undergraduates. Yale encourages their students to venture into unknown academic fields. They provide undergraduates over 1,200 research opportunities in science and technology."),UniversityList(collegeName: "Wright State University", collegeImage: "wsu", collegeInfo: "Wright State University is a public research university in Fairborn, Ohio. Originally opened in 1964 as a branch campus of Miami University and Ohio State University, it became an independent institution in 1967 and was named in honor of aviation pioneers Orville and Wilbur Wright, who were Dayton residents."),UniversityList(collegeName: "Texas State University", collegeImage: "tsu", collegeInfo: "Texas State University is a public research university with its main campus located in the southern portion of the Austin metropolitan area, and its Round Rock campus in the northern portion. ")])



var universityArray = [u1,u2,u3,u4,u5,u6]
